import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "First App",
  description: "Generated by Jairo",
  // openGraph: {
  //   title: "First App",
  //   description: "Generated by Jairo",
  //   url: "https://example.com",
  //   siteName: "First App",
  //   images: [
  //     {
  //       url: "https://example.com/image.png",
  //       width: 800,
  //       height: 600,
  //       alt: "Image Alt Text",
  //     },
  //   ],
  //   locale: "en_US",
  //   type: "website",
  // },
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
